apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-clusterrole
rules:
- apiGroups: ["", "apps", "batch"]
  resources: ["pods", "services", "deployments", "statefulsets", "persistentvolumeclaims", "jobs","nodes"]
  verbs: ["create", "delete", "get", "list", "watch", "patch", "update"]

